### PR TITLE
Update firmware for QT Py on thruhole PCBA

### LINKED ISSUE #7: update firmware for QT Py
firmware to be compiled + flashed onto QT Py on thru-hole PAPRA-PCBA

### PR DESCRIPTION
**Pull request by capsulecorplab**
closes #7

### CODE REVIEW

**Comment by capsulecorplab** [comment]
firmware encounters following compile error as of https://github.com/tetrabiodistributed/papra-pcba-firmware/pull/8/commits/4b9a06bb501e1b0afc0aa65969a38300acdab2d8 Screenshot from 2023-07-06 09-00-24

**Comment by capsulecorplab** [comment]
@mechatroniks-git what version of the Arduino IDE did you flash the firmware on?

**Comment by capsulecorplab** [comment]
same issue on Arduino 2.1.1 
Screenshot from 2023-07-15 00-31-27

**Comment by capsulecorplab** [comment]
firmware compiles, flashes, and prints output to serial after selecting XIAO ESP32C3 board, 
Screenshot from 2023-07-15 11-29-11
Screenshot from 2023-07-15 11-03-33

However, board appears to be fried after couple minutes of operation with m12 + fan

**Comment by mmroden** [comment]
I'd suggest that we have two versions of this code, one for the through-hole board and one for the surface mount board.  They look to do different things and have different chips.

**Comment by mmroden** [comment]
Obviated by PR #11 by having two files, one for surface, one for thruhole.

**Pull request closed without merging**
